blsdjangoproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("cases.urls", namespace="cases")),
]

cases/urls.py
from django.urls import path
from . import views

app_name = "cases" #namespace for the application 

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),

    #URLS for Clients
    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/create/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", views.ClientDeleteView.as_view(), name="client_delete"),

    #URLS for Lawyers
    path("lawyers/", views.LawyerListView.as_view(), name="lawyer_list"),
    path("lawyers/create/", views.LawyerCreateView.as_view(), name="lawyer_create"),
    path("lawyers/<int:pk>/update/", views.LawyerUpdateView.as_view(), name="lawyer_update"),
    path("lawyers/<int:pk>/delete/", views.LawyerDeleteView.as_view(), name="lawyer_delete"),

    #URLS for Cases
    path("cases/", views.CaseListView.as_view(), name="case_list"),
    path("cases/create/", views.CaseCreateView.as_view(), name="case_create"), 
    path("cases/<int:pk>/update/", views.CaseUpdateView.as_view(), name="case_update"),
    path("cases/<int:pk>/delete/", views.CaseDeleteView.as_view(), name="case_delete"),
]

cases/models.py
from django.db import models

# Create your models here.
# class Person(models.Model):
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField(max_length=254)
#     phone = models.CharField(max_length=20)

#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"
#---------------------------------------------------------------------

class Client(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class Lawyer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Case(models.Model):
    STATUS_CHOICES = (
        ('OPEN','Open'),
        ('CLOSED','Closed'),
        ('PENDING','Pending'),
    )

    title = models.CharField(max_length=150)
    description = models.TextField()
    status = models.CharField(max_length=50,choices=STATUS_CHOICES, default='OPEN')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    lawyer = models.ForeignKey(Lawyer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

cases/forms.py
from django import forms
from .models import Client, Lawyer, Case

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["first_name",
                  "last_name",
                  "email",
                  "phone"
                 ]

class LawyerForm(forms.ModelForm):
    class Meta:
        model = Lawyer
        fields = ["first_name",
                  "last_name",
                  "email",
                  "phone"
                 ]

class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ["title",
                  "description",
                  "status",
                  "client",
                  "lawyer"
                ]

cases/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from .models import Client, Lawyer, Case
from .forms import  ClientForm, LawyerForm, CaseForm
# from django.http import HttpResponse
from django.urls import reverse_lazy
##----------------------------------------------------
## landing page 
class HomeView(TemplateView):
    template_name = "home.html"

##----------------------------------------------------
## Client related Views
class ClientListView(ListView):
    model = Client
    template_name = "clients/client_list.html"

class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    template_name = "clients/client_form.html"
    success_url = "/clients/"

class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "clients/client_form.html"
    success_url = "/clients/"

class ClientDeleteView(DeleteView):
    model = Client
    template_name = "clients/client_confirm_delete.html"
    success_url = reverse_lazy("cases:client_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete Client"
        return context

##----------------------------------------------------
## Lawyer related Views
class LawyerListView(ListView):
    model = Lawyer
    template_name = "lawyers/lawyer_list.html"

class LawyerCreateView(CreateView):
    model = Lawyer
    form_class = LawyerForm
    template_name = "lawyers/lawyer_form.html"
    success_url = "/lawyers/"

class LawyerUpdateView(UpdateView):
    model = Lawyer
    form_class = LawyerForm
    template_name = "lawyers/lawyer_form.html"
    success_url = "/lawyers/"

class LawyerDeleteView(DeleteView):
    model = Lawyer
    template_name = "lawyers/lawyer_confirm_delete.html"
    success_url = reverse_lazy("cases:lawyer_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete Lawyer"
        return context

##----------------------------------------------------
## Case related Views
class CaseListView(ListView):
    model = Case
    template_name = "cases/case_list.html"

class CaseCreateView(CreateView):
    model = Case
    form_class = CaseForm
    template_name = "cases/case_form.html"
    success_url = "/cases/"

class CaseUpdateView(UpdateView):
    model = Case
    form_class = CaseForm
    template_name = "cases/case_form.html"
    success_url = "/cases/"

class CaseDeleteView(DeleteView):
    model = Case
    template_name = "cases/case_confirm_delete.html"
    success_url = reverse_lazy("cases:case_list")

cases/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Law Firm Management System</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "cases:home" %}">Law Firm Management System</a>
                <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "cases:client_list" %}">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "cases:lawyer_list" %}">Lawyers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "cases:case_list" %}">Cases</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>

    <main role="main" class="container mt-4">
        {% block content %}
        {% endblock  %}
    </main>
    
    <footer class="bg-primary text-white mt-4 py3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>&copy; {% now 'Y' %} Law Firm Management. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

cases/templates/cases/case_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Delete Case</h2>
    <p>Are you sure you want to delete the case "{{object.title}}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url "cases:case_list" %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}

cases/templates/cases/case_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h1 class="mb-4"> {% if object %}Update{% else %}Add{% endif %} Case</h1>
    <form method="post" novalidate>
        {% csrf_token %}  {% comment %} Generates tokens for security on authentication attack {% endcomment %}
        
        <div class="container form-row">
            <div class="form-group col-md-6">
                <label form="{{ form.title.id_for_label}}">Title:</label>
                <input type="text" class="form-control" id="{{ form.title.id_for_label}}"
                    name="{{ form.title.html_name}}" value="{{ form.title.value|default:'' }}" required>
            </div>
            
            <div class="form-group col-md-6">
                <label for="{{ form.client.id_for_label}}">Client:</label>
                {{ form.client|add_class:"form_control" }}
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="{{ form.lawyer.id_for_label}}">Lawyer:</label>
                    {{ form.lawyer|add_class:"form_control" }}
                </div>
                <div class="form-group col-md-6">
                    <label for="{{ form.status.id_for_label}}">Status:</label>
                    {{ form.status|add_class:"form_control" }}
                </div>
            </div>

            <div class="form-group">
                <label form="{{ form.description.id_for_label}}">Description:</label>
                <textarea class="form-control" id="{{ form.description.id_for_label}}" name="{{ form.description.html_name}}"  
                          rows="5" required>{{ form.description.value|default:'' }}</textarea>
            </div>
            
            <br>
            <div class="form-row">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-seccondary" href="{% url 'cases:case_list' %}">Cancel</a>
            </div>
        </div>
    </form>

{% endblock  %}

cases/templates/cases/case_list.html
{% extends "base.html" %}

{% block content %}
    <h1 class='mb-4'>Cases</h1>
    <a class="btn btn-primary mb-3" href="{% url 'cases:case_create' %}">Add Case</a>

    <table class="table table-striped table-bordered">
        <thread class="thread-dark">
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Client</th>
                <th>Lawyer</th>
                <th>Actions</th>
            </tr>
        </thread>
        <body>
            {% for case in object_list %}
                <tr>
                    <td>{{ case.title }} </td>
                    <td>{{ case.get_status_display }} </td>
                    <td>{{ case.client.pk }}:{{ case.client.first_name }}  {{ case.client.last_name }}  </td>
                    <td>{{ case.lawyer.pk }}:{{ case.lawyer.first_name }}  {{ case.lawyer.last_name }}  </td>
                    <td>
                        <a class="btn btn-info"   href="{% url 'cases:case_update' case.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cases:case_delete' case.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr> <td colspan="4" class="text-center bg-info bg-gradient"> NO CASES FOUND </td> </tr>
            {% endfor %}
        </body>

    </table>

{% endblock content %}

cases/templates/clients/client_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Delete Client</h2>
    <p>Are you sure you want to delete the client "{{object.first_name}} {{object.last_name}}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url "cases:client_list" %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}

cases/templates/clients/client_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h1 class="mb-4"> {% if object %}Update{% else %}Add{% endif %} Client</h1>
    <form method="post" novalidate>
        {% csrf_token %} 
        
        <div class="container form-row">
            <div class="form-group col-md-4">
                <label form="{{ form.first_name.id_for_label}}">First Name:</label>
                <input type="text" class="form-control" id="{{ form.first_name.id_for_label}}"
                    name="{{ form.first_name.html_name}}" value="{{ form.first_name.value|default:'' }}" required>
            </div>
            
            <div class="form-group col-md-4">
                <label form="{{ form.last_name.id_for_label}}">Last Name:</label>
                <input type="text" class="form-control" id="{{ form.last_name.id_for_label}}"
                    name="{{ form.last_name.html_name}}" value="{{ form.last_name.value|default:'' }}" required>
            </div>

            <div class="form-group col-md-4">
                <label form="{{ form.email.id_for_label}}">Email:</label>
                <input type="email" class="form-control" id="{{ form.email.id_for_label}}"
                    name="{{ form.email.html_name}}" value="{{ form.email.value|default:'' }}" required>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label form="{{ form.phone.id_for_label}}">Phone:</label>
                    <input type="text" class="form-control" id="{{ form.phone.id_for_label}}"
                        name="{{ form.phone.html_name}}" value="{{ form.phone.value|default:'' }}" required>
                </div>
            </div>
            <br>
            <div class="form-row">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-seccondary" href="{% url 'cases:client_list' %}">Cancel</a>
            </div>
        </div>
    </form>

{% endblock  %}

cases/templates/clients/client_list.html
{% extends "base.html" %}

{% block content %}
    <h1 class='mb-4'>Clients</h1>
    <a class="btn btn-primary mb-3" href="{% url 'cases:client_create' %}">Add Client</a>

    <table class="table table-striped table-bordered">
        <thread class="thread-dark">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Actions</th>
            </tr>
        </thread>
        <body>
            {% for client in object_list %}
                <tr>
                    <td>{{ client.pk }} </td>
                    <td>{{ client.first_name }} {{ client.last_name }} </td>
                    <td>{{ client.email }} </td>
                    <td>{{ client.phone }} </td>
                    <td>
                        <a class="btn btn-info"   href="{% url 'cases:client_update' client.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cases:client_delete' client.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr> <td colspan="4" class="text-center"> NO CLIENTS FOUND </td> </tr>
            {% endfor %}
        </body>

    </table>

{% endblock content %}

cases/templates/home.html
{% extends "base.html" %}

{% block  content %}
    <div class="jumbotron">
        <h1 class="display-7">Welcome to Law Firm Management!</h1>
        <p class="lead">This is a tutorial Law firm project built using Django</p>
        <hr class="my-4">

        <p>Use the Navigation menu below to manage client, layers and cases.</p>
        <a class="btn btn-info btn-sm" role="button" href="{% url "cases:client_list" %}">View Clients</a>
        <a class="btn btn-info btn-sm" role="button" href="{% url "cases:lawyer_list" %}">View Lawyers</a>
        <a class="btn btn-info btn-sm" role="button" href="{% url "cases:case_list" %}">View Cases</a>
    </div>
{% endblock  %}

cases/templates/lawyers/lawyer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h2>Delete Lawyer</h2>
    <p>Are you sure you want to delete the Lawyer "{{object.first_name}} {{object.last_name}}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url "cases:lawyer_list" %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}

cases/templates/lawyers/lawyer_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h1 class="mb-4"> {% if object %}Update{% else %}Add{% endif %} Lawyer</h1>
    <form method="post" novalidate>
        {% csrf_token %} 
        
        <div class="container form-row">
            <div class="form-group col-md-4">
                <label form="{{ form.first_name.id_for_label}}">First Name:</label>
                <input type="text" class="form-control" id="{{ form.first_name.id_for_label}}"
                    name="{{ form.first_name.html_name}}" value="{{ form.first_name.value|default:'' }}" required>
            </div>
            
            <div class="form-group col-md-4">
                <label form="{{ form.last_name.id_for_label}}">Last Name:</label>
                <input type="text" class="form-control" id="{{ form.last_name.id_for_label}}"
                    name="{{ form.last_name.html_name}}" value="{{ form.last_name.value|default:'' }}" required>
            </div>

            <div class="form-group col-md-4">
                <label form="{{ form.email.id_for_label}}">Email:</label>
                <input type="email" class="form-control" id="{{ form.email.id_for_label}}"
                    name="{{ form.email.html_name}}" value="{{ form.email.value|default:'' }}" required>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label form="{{ form.phone.id_for_label}}">Phone:</label>
                    <input type="text" class="form-control" id="{{ form.phone.id_for_label}}"
                        name="{{ form.phone.html_name}}" value="{{ form.phone.value|default:'' }}" required>
                </div>
            </div>
            <br>
            <div class="form-row">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-seccondary" href="{% url 'cases:lawyer_list' %}">Cancel</a>
            </div>
        </div>
    </form>

{% endblock  %}

cases/templates/lawyers/lawyer_list.html
{% extends "base.html" %}

{% block content %}
    <h1 class='mb-4'>Lawyers</h1>
    <a class="btn btn-primary mb-3" href="{% url 'cases:lawyer_create' %}">Add Lawyer</a>

    <table class="table table-striped table-bordered">
        <thread class="thread-dark">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Actions</th>
            </tr>
        </thread>
        <body>
            {% for lawyer in object_list %}
                <tr>
                    <td>{{ lawyer.pk }} </td>
                    <td>{{ lawyer.first_name }} {{ lawyer.last_name }} </td>
                    <td>{{ lawyer.email }} </td>
                    <td>{{ lawyer.phone }} </td>
                    <td>
                        <a class="btn btn-info"   href="{% url 'cases:lawyer_update' lawyer.pk %}">Update</a>
                        <a class="btn btn-danger" href="{% url 'cases:lawyer_delete' lawyer.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr> <td colspan="4" class="text-center"> NO LAWYERS FOUND </td> </tr>
            {% endfor %}
        </body>

    </table>

{% endblock content %}